# Generated by Django 4.0.4 on 2022-05-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_name', models.CharField(max_length=100)),
                ('members_position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='pages.aboutus')),
            ],
            options={
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='pages.aboutus')),
            ],
            options={
                'verbose_name_plural': 'Our services',
            },
        ),
    ]
