# Generated by Django 4.0.4 on 2022-06-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_slug_category_slug_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_category',
            new_name='slug',
        ),
    ]
